### ISSUE TITLE
Add Github Action to build and test the project instead of travis

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/brackit#18]

**Comment by RishiKumarRay** [comment]
I would like to give a try for this

**Comment by RishiKumarRay** [comment]
Hey , I am getting this error while setting up github action , Do you have any idea regarding this
![Screenshot from 2022-01-18 04-09-02](https://user-images.githubusercontent.com/87641376/149844462-53dac3b6-c955-4011-a09a-8dd72e0368f1.png)

**Comment by JohannesLichtenberger** [comment]
I think you need the most recent maven version for Java 17.
