### ISSUE TITLE
Implement a JsonDoc function similar to FnDoc

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/brackit#23]

**Comment by AjRadwan** [comment]
Can you  tell me where should Implement this function

**Comment by JohannesLichtenberger** [comment]
There's a doc function for XML: https://github.com/sirixdb/brackit/blob/master/src/main/java/org/brackit/xquery/function/fn/Doc.java

It can be implemented very similar to this function, but we first have to implement a `SimpleJsonStore` and a `JsonCollection` analogous to the SimpleStore for XML. Maybe you can work on this together with @mosheduminer :-)

**Comment by JohannesLichtenberger** [comment]
It should be in the JSON package :-)

**Comment by JohannesLichtenberger** [comment]
Depends on issue #22 and #21.

I've added `SimpleJsonStore` and `SimpleJsonCollection` classes which have to be implemented first. They are supposed to be in-memory instances.

**Comment by AjRadwan** [comment]
Hello @mosheduminer  do you wanna work on it together?  
I'd love to Work with you.

**Comment by mosheduminer** [comment]
@AjRadwan sorry for the delay in response. You're welcome to work on it, and we can collaborate over github (or, if you prefer, on the slack or discord (linked in the readme)).

**Comment by AjRadwan** [comment]
@mosheduminer   I am travelling now so I will get back to you on discord before Monday,  I am replying this form my mobile phone :).

**Comment by mosheduminer** [comment]
Hey @AjRadwan, I needed that `jn:doc()` function, so I ended up implementing it myself. You're welcome to work on other issues here though.
