### ISSUE TITLE
Examples attempts to instantiate QueryContext

### ISSUE THREAD

**Issue by AlvinKuruvilla** [sirixdb/brackit#36]
In [Simple.java](https://github.com/sirixdb/brackit/blob/0e7d7bf8e4f0ff38ce173c033dadb22f280726f2/src/examples/java/org/brackit/examples/Simple.java#L57), for example this line is used:
```java
    QueryContext ctx = new QueryContext();
```
However, when running the file with 
```java
javac -cp target/brackit-0.1.11-SNAPSHOT-jar-with-dependencies.jar src/examples/java/org/brackit/examples/Simple.java
```
We get the following error:
```java
src/examples/java/org/brackit/examples/Simple.java:57: error: QueryContext is abstract; cannot be instantiated
    QueryContext ctx = new QueryContext();
                       ^
```

**Comment by mosheduminer** [comment]
The examples definitely need to be updated - in this case, you need to use `BrackitQueryContext` I think.

**Comment by JohannesLichtenberger** [comment]
I think I've changed all occurrences, but I'm at my tablet...

**Comment by AlvinKuruvilla** [comment]
I managed to get it to [compile](https://github.com/AlvinKuruvilla/brackit/commit/142ef46960a3a99a65d3b65613c3d53c7f519013), but it doesn't output anything to the screen. I suspect it has something to do with the finagling I did [here](https://github.com/AlvinKuruvilla/brackit/blob/142ef46960a3a99a65d3b65613c3d53c7f519013/src/examples/java/org/brackit/examples/Simple.java#L73). 
I wasn't very sure how to use 
```java
PrintWriter()
``` 
with
```java
SubtreePrinter()
```

**Comment by JohannesLichtenberger** [comment]
I've fixed the examples. Can you verify that they work, please? :+1:

**Comment by AlvinKuruvilla** [comment]
Just tried running the examples. I used:
```java
javac -cp target/brackit-0.1.11-SNAPSHOT-jar-with-dependencies.jar src/examples/java/org/brackit/examples/Simple.java
```
and it doesn't print anything to the screen

**Comment by JohannesLichtenberger** [comment]
```java
java -cp target/brackit-0.1.11-SNAPSHOT-jar-with-dependencies.jar src/examples/java/org/brackit/examples/Simple.java
```

this one does :-) (without the `c`) you're only compiling

**Comment by AlvinKuruvilla** [comment]
😅
